/*
 * 参加中の占いプログラム一覧
 *
 * 追加方法:
 * 1. A8.netで参加中・掲載媒体・広告素材の有効性を確認
 * 2. 下の配列へ1件追加
 * 3. statusを "active" にすると、typeに対応する一覧へ自動表示
 *
 * type: phone / chat / mail / comprehensive
 * status: active のみ公開。pending / paused は公開されません。
 */
window.FORTUNE_PROGRAMS = [
  {
    id: "coconala",
    name: "ココナラ電話占い",
    brand: "COCONALA",
    type: "phone",
    status: "active",
    featured: true,
    asp: "A8.net",
    verifiedAt: "2026-07-19",
    label: "相談相手の情報を見て選びたい人に",
    featureTitle: "出品者情報と相談テーマから、自分に合いそうな相手を探せる",
    featurePoints: ["候補を比較しやすい", "対面せず電話相談", "予算から検討しやすい"],
    description: "出品者情報や相談テーマを見比べて、対面せず電話で相談したい人向けです。",
    fit: "相談テーマと予算を決め、候補を比較して選びたい人",
    avoid: "時間や支出を自分で止めにくい人／専門判断が必要な人",
    checks: "占い師ごとの1分料金・通話料・特典上限・キャンセル条件",
    affiliateUrl: "https://px.a8.net/svt/ejp?a8mat=4B7ROY+2BY52Q+2PEO+C5VW1",
    trackingPixel: "https://www17.a8.net/0.gif?a8mat=4B7ROY+2BY52Q+2PEO+C5VW1",
    cta: "ココナラの公式条件を見る",
    visual: "visual-chat"
  },
  {
    id: "vernis",
    name: "電話占いヴェルニ",
    brand: "VERNIS",
    type: "phone",
    status: "active",
    featured: false,
    asp: "A8.net",
    verifiedAt: "2026-07-19",
    label: "在籍占い師の選択肢を広く見たい人に",
    featureTitle: "幅広い候補から、相談内容や条件に合う占い師を絞り込める",
    featurePoints: ["在籍候補を広く比較", "相談内容から検討", "予約条件も確認できる"],
    description: "在籍占い師の選択肢を広く見ながら、相談内容や条件に合う候補を探したい人向けです。",
    fit: "複数の占い師を比較してから電話相談したい人",
    avoid: "文章だけで相談したい人／予算上限を決めにくい人",
    checks: "1分料金・通話料・初回特典・予約・支払方法",
    affiliateUrl: "https://px.a8.net/svt/ejp?a8mat=4B7ROY+EAFAQ+2H0Q+TUVZL",
    trackingPixel: "https://www18.a8.net/0.gif?a8mat=4B7ROY+EAFAQ+2H0Q+TUVZL",
    cta: "ヴェルニの公式条件を見る",
    visual: "visual-phone"
  },
  {
    id: "spacia",
    name: "恋愛応援スペーシア",
    brand: "SPACIA",
    type: "phone",
    status: "active",
    featured: false,
    asp: "A8.net",
    verifiedAt: "2026-07-19",
    label: "恋愛の悩みを電話で話したい人に",
    featureTitle: "片想い・復縁・夫婦関係など、恋愛テーマから相談先を探しやすい",
    featurePoints: ["恋愛テーマを中心に相談", "電話でその場で話せる", "初回向け条件を確認できる"],
    description: "文章だけでは整理しにくい恋愛の悩みを、電話で話しながら相談したい人向けです。",
    fit: "片想い・復縁・夫婦関係などを、声で話しながら整理したい人",
    avoid: "相談内容を文章で残したい人／未成年者／予算上限を決めにくい人",
    checks: "1分料金・通話料・無料鑑定の対象条件・利用時間・キャンセル条件",
    affiliateUrl: "https://px.a8.net/svt/ejp?a8mat=4B8096+5IUSTU+3SKE+60H7M",
    trackingPixel: "https://www12.a8.net/0.gif?a8mat=4B8096+5IUSTU+3SKE+60H7M",
    cta: "スペーシアの公式条件を見る",
    visual: "visual-phone"
  },
  {
    id: "brillante",
    name: "チャット占い ブリランテ",
    brand: "BRILLANTE",
    type: "chat",
    status: "active",
    featured: false,
    asp: "A8.net",
    verifiedAt: "2026-07-19",
    label: "リアルタイムの文章相談をしたい人に",
    featureTitle: "先生のプロフィールを確認して、リアルタイムチャットで相談できる",
    featurePoints: ["文章でリアルタイム相談", "先生の情報から選べる", "相談内容を声に出さなくてよい"],
    description: "電話では話しにくい内容を、先生を選んでリアルタイムの文章で相談したい人向けです。",
    fit: "声を出しにくい場所から、文章でテンポよく相談したい人",
    avoid: "長い経緯を事前にまとめたい人／コイン購入額を管理しにくい人",
    checks: "コイン価格・鑑定の課金単位・対応時間・追加購入・退会条件",
    affiliateUrl: "https://px.a8.net/svt/ejp?a8mat=4B8096+757A42+5SGG+5YRHE",
    trackingPixel: "https://www13.a8.net/0.gif?a8mat=4B8096+757A42+5SGG+5YRHE",
    cta: "ブリランテの公式条件を見る",
    visual: "visual-chat"
  },
  {
    id: "miror",
    name: "MIROR（ミラー）",
    brand: "MIROR",
    type: "mail",
    status: "active",
    featured: false,
    asp: "A8.net",
    verifiedAt: "2026-07-19",
    label: "相談内容を文章でまとめたい人に",
    featureTitle: "得意分野や鑑定メニューを見ながら、文章形式の相談先を選べる",
    featurePoints: ["メニュー単位で比較", "文章で背景を伝えられる", "鑑定内容を読み返しやすい"],
    description: "恋愛や将来の経緯を自分のペースで書き、鑑定メニューから相談先を選びたい人向けです。",
    fit: "複雑な背景を文章で伝え、鑑定内容をあとから読み返したい人",
    avoid: "電話ですぐ話したい人／回答を待つのが難しい人",
    checks: "メニュー価格・回答時期・追加質問の範囲・キャンセル条件・相談形式",
    affiliateUrl: "https://px.a8.net/svt/ejp?a8mat=4B8096+76ZKXE+4PWE+C0B9U",
    trackingPixel: "https://www12.a8.net/0.gif?a8mat=4B8096+76ZKXE+4PWE+C0B9U",
    cta: "MIRORの公式条件を見る",
    visual: "visual-mail"
  },
  {
    id: "coconala-text",
    name: "ココナラ占い（テキスト相談）",
    brand: "COCONALA TEXT",
    type: "mail",
    status: "active",
    featured: false,
    asp: "A8.net",
    verifiedAt: "2026-07-19",
    label: "価格や納期を見比べて選びたい人に",
    featureTitle: "出品形式の占いメニューから、価格・内容・提供条件を比較して選べる",
    featurePoints: ["テキスト相談が中心", "出品メニューを比較", "価格と納期を確認しやすい"],
    description: "複数の出品サービスを見比べ、相談テーマ・価格・納期から選びたい人向けです。",
    fit: "相談内容を文章で送り、サービスごとの条件を比較して選びたい人",
    avoid: "電話で今すぐ話したい人／出品者ごとの条件確認が負担な人",
    checks: "サービス価格・納期・質問回数・出品者情報・キャンセル条件",
    affiliateUrl: "https://px.a8.net/svt/ejp?a8mat=4B8096+5FA776+2PEO+1BP8ZM",
    trackingPixel: "https://www12.a8.net/0.gif?a8mat=4B8096+5FA776+2PEO+1BP8ZM",
    cta: "ココナラのテキスト相談条件を見る",
    visual: "visual-mail"
  }
];
